Add new "GameMode" option which implements org.freedesktop.portal.GameMode
vinegarhq/vinegar pull request #284
Opened 2023-11-23 19:45 UTC by Noted-Jrelvas

Currently, users have to manually edit configuration to use gamemode by setting a custom launcher. This is bad because the majority of distros have gamemode present. Furthermore, our flatpak requires an extension to be installed separately for `gamemoderun` to be available, which further degrades user experience.

This PR fixes that by implementing support for requesting gamemode to be enabled via desktop portals, which is done by default (for both player and studio). This should work out of the box for most distros and for flatpak installs.

Note: VinegarBridge will depend on the new `internal/bus` package for some of its functionality, so this PR is a prerequisite for implementing it.

2023-11-23 19:50 UTC, Noted-Jrelvas commented
Systems without dbus and/or desktop portals will simply not use this new functionality. There should be no regressions.

2023-11-23 23:22 UTC, apprehensions requested changes

2023-11-23 23:22 UTC, apprehensions commented on internal/bus/gamemode.go
> +	return true, nil
```suggestion
	return response > 0, nil
```

2023-11-23 23:22 UTC, apprehensions commented on internal/bus/bus.go
> +	return session
```suggestion
	session := &SessionBus{
		conn: conn,
		portal: conn.Object("org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop"),
	}
```

2023-11-23 23:22 UTC, apprehensions commented on config/config.go
> +	GameMode      bool        `toml:"gamemode"`
`go fmt`

2023-11-24 15:07 UTC, Noted-Jrelvas commented on config/config.go
> +	GameMode      bool        `toml:"gamemode"`
Fixed by 0bebc3d6f4f72cec8b792f5c693fd05de886cf41

2023-11-24 15:15 UTC, Noted-Jrelvas commented
I've applied your feedback and suggestions. I'm ready for a second review.

2023-11-24 22:38 UTC, apprehensions requested changes

2023-11-24 22:38 UTC, apprehensions commented on internal/bus/bus.go
> +	return nil
```suggestion
	call := s.portal.Call("org.freedesktop.portal.GameMode.RegisterGame", 0, pid)
	if call.Err != nil && !errors.Is(call.Err, dbus.ErrMsgNoObject) {
		return call.Err
	}

	return nil
```

2023-11-24 22:38 UTC, apprehensions commented on internal/bus/bus.go
> +func (s *SessionBus) GamemodeRegister(pid int) (error) {
```suggestion
func (s *SessionBus) GamemodeRegister(pid int32) (error) {
```

2023-11-24 22:44 UTC, Noted-Jrelvas commented on internal/bus/bus.go
> +func (s *SessionBus) GamemodeRegister(pid int) error {
```suggestion
func (s *SessionBus) GamemodeRegister(pid int32) error {
```

2023-11-24 22:46 UTC, Noted-Jrelvas commented on internal/bus/bus.go
> +func (s *SessionBus) GamemodeRegister(pid int) (error) {
Fixed.

2023-11-24 23:03 UTC, apprehensions approved these changes

2023-11-27 07:59 UTC, lunarlettuce approved these changes

2023-11-27 08:00 UTC, merged

2023-12-09 23:15 UTC, RackYican commented
It is actived by default or we need to activate it?

2023-12-09 23:21 UTC, Noted-Jrelvas commented
It's active by default